# action名称
name: Publish and Release

# 当代码合并到main分支的时候，执行下列脚本
on:
  push:
    branches: [main]
# 任务
jobs:
  publish-npm:
    #运行时所需要的虚拟机环境
    runs-on: ubuntu-latest
    steps:
      - name: 检查main分支
        uses: actions/checkout@main

      - name: 安装Node.js
        uses: actions/setup-node@main
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/ # 如果不配置将影响publish

      - name: 安装依赖
        run: npm install --force

      - name: 打包库
        run: npm run lib

      - name: 发布NPM包
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm publish
      - name: publish 成功通知
        run: echo npm 推送成功，请访问 https://jsonlyh.github.io/agility-form-doc

      - name: 读取当前版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version

      - name: 创建GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          #无需自己去生成
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{steps.version.outputs.value}}
          release_name: v${{steps.version.outputs.value}}
          draft: false
          prerelease: false

      - name: 打包生成文档
        run: npm run docs:build

      - name: 准备项目文档环境
        run: |
          mkdir ./dist/docs
          cp ./dist/agility-form-doc ./dist/docs
          cp ./README.md ./dist/docs
          cp ./CHANGELOG.md ./dist/docs

      - name: 发布到文档仓库
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: jsonlyh.github.io
          BRANCH: master
          FOLDER: ./dist/docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 文档生成成功通知
        run: echo npm 文档上传成功，请访问 https://jsonlyh.github.io/agility-form-doc